# Generated by Django 5.0 on 2024-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_video",
            field=models.CharField(max_length=50),
        ),
    ]
