# Generated by Django 4.1.7 on 2023-03-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
    ]
