# Generated by Django 4.0.3 on 2022-03-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
