# Generated by Django 4.1.2 on 2022-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
